commit_message: '[skip ci] Update translations (%language%) %original_file_name%'
pull_request_title: 'i18n: update translations'
pull_request_labels:
  - i18n
files:
  - source: /src/**/*.md
    translation: /src/%locale%/**/%file_name%.md
    ignore:
      - /src/en/
      - /src/ja/
      - /src/ko/
      - /src/fr/
  - source: /.vitepress/locales/zh.ts
    translation: /.vitepress/locales/%locale%.ts
